### ISSUE TITLE
TilesetManager not pushed? 

### ISSUE THREAD

**Issue by volkanbektas** [teamzac/laravel-tileserver#1]
I'm currently trying to run your laravel tile server project but there is missing the TilesetManager or did I missed something?

**Comment by chadjanicek** [comment]
Hmm, let me take a look. That may have been something from an older version that I should remove. Will get back to you.

**Comment by chadjanicek** [comment]
Yeah, I think this is just something that should have been removed. Initially we were going to use Laravel's Manager class to allow extending the package for data providers other than Mbtiles, but as we started building it out we decided not to do that since _we_ only need to handle Mbtiles databases. You can still provide a custom provider to the ```Tileset``` constructor, it just doesn't extend from Laravel's Manager class anymore. Sorry for the confusion; I've updated the package to reflect this.

We haven't had to touch this package in a while because it's working just fine for us, but if you're having any problems getting it to work just let me know and I'll do my best to help. Thanks!
